<a href="https://colab.research.google.com/github/michaelnonso/data-analytics/blob/main/Predict_Patient_Smoking_Status.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

OBJECTIVE

- To use binary classification to predict a patient's smoking status given information about various other health indicators.

Import Pakages

In [ ]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf


Reading Test and Train Data/ Data Wrangling

In [ ]:
dataset_train = pd.read_csv('/content/drive/MyDrive/keggle-competition/train.csv')
dataset_test = pd.read_csv('/content/drive/MyDrive/keggle-competition/test.csv')


In [ ]:
X_predict = dataset_test.iloc[:, 1:].values


In [ ]:
X = dataset_train.iloc[:, 1:-1].values
y_train = dataset_train.iloc[:, :-1].values

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building Elastic NET

In [ ]:
from sklearn.linear_model import ElasticNet
# Create an ElasticNet object with l1_ratio=0.5
model = ElasticNet(l1_ratio=0.3)

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 1]
 [0 1]]


LOGISTIC REGRESSION

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

ANN

In [ ]:
# Part 2 - Building the ANN

# Initializing the ANN
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
3982/3982 [==============================] - 14s 3ms/step - loss: 0.4915 - accuracy: 0.7459
Epoch 2/100
3982/3982 [==============================] - 8s 2ms/step - loss: 0.4663 - accuracy: 0.7653
Epoch 3/100
3982/3982 [==============================] - 9s 2ms/step - loss: 0.4623 - accuracy: 0.7682
Epoch 4/100
3982/3982 [==============================] - 8s 2ms/step - loss: 0.4603 - accuracy: 0.7697
Epoch 5/100
3982/3982 [==============================] - 9s 2ms/step - loss: 0.4592 - accuracy: 0.7707
Epoch 6/100
3982/3982 [==============================] - 8s 2ms/step - loss: 0.4585 - accuracy: 0.7704
Epoch 7/100
3982/3982 [==============================] - 9s 2ms/step - loss: 0.4581 - accuracy: 0.7712
Epoch 8/100
3982/3982 [==============================] - 7s 2ms/step - loss: 0.4578 - accuracy: 0.7712
Epoch 9/100
3982/3982 [==============================] - 10s 2ms/step - loss: 0.4577 - accuracy: 0.7713
Epoch 10/100
3982/3982 [==============================] - 7s 2ms/step -

Predicting The Test Set Results

In [ ]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

996/996 [==============================] - 2s 2ms/step
[[0 0]
 [1 0]
 [1 1]
 ...
 [0 0]
 [0 1]
 [0 1]]


CONCATENATING PREDICTED AND REAL TEST RESULT

In [ ]:

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [1 1]
 ...
 [0 0]
 [0 1]
 [0 1]]


CONFUSION MATRIX

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13435  4247]
 [ 3774 10396]]


0.7481790782368454

FINAL PREDICTION

In [ ]:
y_predicted = classifier.predict(X_predict)
print(y_predicted.reshape(len(y_predicted),1))

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
